version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: weekly
    time: "20:00"
  open-pull-requests-limit: 10
  target-branch: update-dependencies
  allow:
  - dependency-type: direct
  - dependency-type: indirect
  ignore:
  - dependency-name: connection_pool
    versions:
    - 2.2.4
  - dependency-name: listen
    versions:
    - 3.5.1
  - dependency-name: mimemagic
    versions:
    - 0.3.10
  - dependency-name: rspec-rails
    versions:
    - 5.0.0
  - dependency-name: sidekiq
    versions:
    - 6.2.0
  - dependency-name: rails
    versions:
    - 6.1.1
    - 6.1.2
    - 6.1.2.1
    - 6.1.3
  - dependency-name: nio4r
    versions:
    - 2.5.7
  - dependency-name: puma
    versions:
    - 5.2.0
  - dependency-name: msgpack
    versions:
    - 1.4.2
  - dependency-name: rspec-support
    versions:
    - 3.10.2
